name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
      # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

        # Deploy ARM template
      - name: Run ARM deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG_ARM }}
          template: ./azure-arm-deploy.json

        # output containerName variable from template
      - run: echo ${{ steps.deploy.outputs.containerName }}

      build-and-deploy:
      runs-on: ubuntu-latest
      steps:
      # checkout the repo
      - name: 'Checkout GitHub Action' 
        uses: actions/checkout@main
    
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Setup Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      - name: 'npm install, build, and test'
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
                
      # deploy web app using Azure credentials
      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'webApp-n2zxwcrdxol4c'
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      # Azure logout 
      - name: logout
        run: |
          az logout